### ISSUE TITLE
Bubble sides looking smaller than the center

### ISSUE THREAD

**Issue by dgkngk** [hohmannr/bubblified#10]
![image](https://user-images.githubusercontent.com/44444834/131227389-c0f4fccb-3cb3-4cbc-8e65-55d2d75d889e.png)
 
Hello, I installed zsh for the first time recently and after seeing your theme on reddit I tried to give it a whirl, but no matter what I tried I couldn't get the sides of the bubbles right. Any suggestions on how to fix this?

**Comment by dgkngk** [comment]
so apparently using nerd fonts manual instructions are harder than using AUR, and I had messed it up. I tried installing nerd fonts' source code pro with yay and the problem went away.

**Comment by hohmannr** [comment]
Glad you solved the issue. For people reading this post close: The font you are using must be able to stretch the full line height and your terminal emulator must support this font stretching.
