### ISSUE TITLE
Can I use antigen for installation?

### ISSUE THREAD

**Issue by ywpkwon** [hohmannr/bubblified#4]
Can I use `antigen` (https://github.com/zsh-users/antigen) to apply this theme, so that users simply apply like `antigen theme hohmannr/bubblified`? I think then more people can enjoy this awesome theme. Please consider this.

For example, currently I'm using spaceship-prompt (denysdovhan/spaceship-prompt) using `antigen`.

**Comment by hohmannr** [comment]
This is a good idea, I have not thought about this, but will consider this in a future update.

**Comment by hohmannr** [comment]
Antigen is awesome and already compatible with this theme. For me it worked without changing anything. I will update the README.
